### PR TITLE
Fix for that weird authcode thingy.

### PR DESCRIPTION
**Pull request by 7kasper**
Another fun thing...
Let's hope they keep this static.

### CODE REVIEW

**Comment by tamarpostma** [comment]
Pretty sure I should not be commenting here. So, apologies for using this as social media..
I have been using Magbot perfectly for ages as a teacher but yesterday I accidentally merged the calendars in OS X and they stopped working. Tried to make a new account on the old Magbot and then found the new beta. Although login is successful it does not show calendars in any accounts. Also for my son, who is a student, it does also activate but no cal show.
Do you know if this is a magister thing or am I doing something stupid? 
Would appreciate the help.

**Comment by lieuwex** [comment]
@7kasper @stanvk seems like your project?

**Comment by Sj3rd** [comment]
The beta is @7kasper and mine. We're working on it, but is has been on freeze for time. When @7kasper fixes the database it will replace the old Magbot. :)

**Comment by tamarpostma** [comment]
Ok, great. Appreciate the update. Will gladly wait for it! Thanks for the good work.

Verstuurd vanaf mijn iPhone

**Comment by Sj3rd** [comment]
Also, it has full support for parents now (and more cool extras like email notifications a week before a test)

**Comment by tamarpostma** [comment]
Excellent! Looking forward to it!

Verstuurd vanaf mijn iPhone

**Comment by 7kasper** [comment]
@tamarpostma like @Sj3rd said we are almost done with the new magbot. If you want it will be fixed there. Meanwhile your best option is to login on magbot.nl and delete your account. You should still be able to register there and your account will be ported to the new magbot in a few days.

**Comment by tamarpostma** [comment]
Hi Kasper,
thanks for your.

I have done all that you mentioned but could not get back in to the old magbot.
The school name is groevenbeek.magister.net, so school name is groevenbeek?
And then my normal magister log in.
Alas, to no avail...

Any suggestions are welcome of course.

**Comment by tamarpostma** [comment]
Last try?
As you can see, this is what I get when I log in. 
This always worked perfectly until yesterday.
Now I’m wondering if perhaps I’m filling in the wrong info. 
School: groevenbeek (full address is groevenbeek.magister.net)
Username: [normal magister abbreviation]
Password: [normal magister password]

I’m pretty sure it’s something I’ve overlooked, or perhaps because I added it years ago when it was still magister 5? 

Well, maybe you have time to look at this, and if not, that’s ok too!

**Comment by Sj3rd** [comment]
Oh, @7kasper, misschien zit in de signup functie nog niet de versie met de authCode

**Comment by 7kasper** [comment]
@tamarpostma yeah it seems something broke on my end related also to new authcode. It should work now.

**Comment by Sj3rd** [comment]
Also, @tamarpostma, zou je in de nieuwe magbot een docenten feature willen, dat je ook de klas in de afspraak ziet? Een voorbeeld van een afspraak die de nieuwe magbot erin zou zetten is: **Nederlands van F. Hengst**

En als er dan en docenten modus zou komen, hoe zou je dan de afspraak erin willen hebben?

image

**Comment by tamarpostma** [comment]
Wow! It works. Thanks for this.
Is this all voluntary work? You should ask a user fee.
Would well be worth it..😎

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Bedoel je dat ik als docent zoiets zou zien?:

A4A
9:10am, 234a

**Comment by tamarpostma** [comment]
Hmm…
It’s activating and all, but not seeing the appointments in google. Does this take a while?

**Comment by Sj3rd** [comment]
@tamarpostma lets move this thread over to https://github.com/mamorgen/magbot3/issues/6 please.

**Comment by tamarpostma** [comment]
got it..

**Pull request merged**
