### PR TITLE
Cleanup the login flow

### PR DESCRIPTION
**Pull request by idiidk**
I tried to make it as logical as possible, moved some bits to the utils files. I also tried to make as much use of the querystring library provided with node as possible, it's a lot safer than just using splits. I know it's not perfect yet but I tried to make it at least a bit more understandable.

### CODE REVIEW

**Comment by idiidk** [comment]
I just realized I hit my auto format button at least once, sorry about that. I know the commit is hard to read now, hopefully it's not too bad at least.

**Comment by LevitatingBusinessMan** [comment]
What happned with the test [here](https://github.com/simplyGits/MagisterJS/pull/142/files#diff-c1129c8b045390789fa8ff62f2c6b4a9L405). Anyway, all the changes look great. But although I am not the author of the repo but I think it'd be appreciated if you make more specific PR's.

Right now this is a PR completely redoing the Authorization but also changing stuff to the tests, editing the appointments and doing some refactoring here and there. Which is kind of bad practice, and messes a bit with the commit history.

**Comment by idiidk** [comment]
Thanks for the tips, I'll close this one and redo it. Working while tired fucks up more than it fixes. Dont know what happened to the test, also dont know what happened to Travis. Probably another stupid mistake :).

Also, for next time, how should I build PR's? Because if it's a big issue and I follow your advice there would be a lot of them for every little thing that's fixed. Or isnt that a problem?

**Comment by LevitatingBusinessMan** [comment]
When I am planning on making one or more pull request I like to focus on one issue first, create a branch for it in my fork. Add commits to it, big commits are fine as long as the changes are related. If a single commit has multiple unrelated changes in it it gets harder to roll it back (just like PRs) and should probably be split in multiple commits. Then create the PR, smaller PRs are just easier to review because there are less things to look at and you can test it easier. But it also makes it easier to roll changes back because you can just safely roll back all commits from a single PR and it makes sure you can approve one change but disapprove another. If you want to make multiple changes to someones codebase create a branch for each pull request in your fork.

This way, especially for bigger repositories with hundreds of open pull requests you have a way better change to be reviewed at all.

[Here](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)'s an article discussing it. It isn't a big as a deal as I am making it sound, I just wanted to put my 2 cents in.

**Comment by idiidk** [comment]
Thanks man, that's awesome to hear! I hope to finish the kahoot shit soon. And I know you were just giving tips, don't worry, I really appreciate it.

**Pull request closed without merging**
