### PR TITLE
OpenID Authentication - Alpha 2

### PR DESCRIPTION
**Pull request by idiidk**
- Added OpenID authentication
- Switched from Session ID's to Bearer tokens
- Rewrote some of the HTTP wrapper code to allow options in get requests
- Upgraded node-fetch to allow redirect header extraction
- Upgraded to Node 6 build target to allow async functions

### CODE REVIEW

**Comment by idiidk** [comment]
Should close #73

**Comment by lieuwex** [comment]
woops sorry for the noise, i'm having some troubles lol

**Comment by idiidk** [comment]
Thank you, I know the style changes were not really  supposed to be in the same commit but it was late and the tests passed so I didn't really think about it lol. Being a maintainer would be great! Is there a roadmap or something before v2 is finished? I could look at implementing some of those features or fix some more bugs.

**Comment by lieuwex** [comment]
Well we have https://github.com/simplyGits/MagisterJS/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0 for some issues that should'be fixed before v2 is done. But I think we're also still missing some functionality from v1. You can take a look to every class in v1 and see whatever seems to be missing in v2. I can also take a look if you want

**Pull request merged**
