### PR TITLE
authcode changed

### PR DESCRIPTION
**Pull request by Sj3rd**
we need a parser :( 

f*ck schoolmaster

### CODE REVIEW

**Comment by lieuwex** [comment]
This certainly is a cat and mouse game. Do we really want to merge this or would it be better to add this auth code as a parameter for users to fill in?

In the end we really want to have a parser or something like that, but should we merge this or just add a parameter?

**Comment by lieuwex** [comment]
Looking at the code they are really trying to generate the code in a convoluted manner, no idea why they want to make it so artificially hard, it's sad. We can try to get extract it really, but maybe it's better to just spin up some worker every day which tries to extract the ID and injects it into a seperate npm package which gets included.

**Comment by Argetan** [comment]
I was thinking something like this, but I'll leave it up to you. `some.url` would of course point to the JSON file containing the authentication code. This way the only file that needs to be updated is the JSON file, no need to update NPM packages or such.

```js
const request = require('request');

var auth_code;

request('https://some.url', { json: true }, (err, res, body) => {
  if (err) { return console.log(err); }
  auth_code = body.authCode;
});
```

**Comment by lieuwex** [comment]
@Argetan I've chosen for the npm package idea since I don't really like having an external runtime dependency on an http endpoint. I feel like magisterjs should only depend on the state of the magister server. Not any other server, somebody also has to make sure it keeps running for basically indefinitely.

**Comment by lieuwex** [comment]
@Sj3rd @Argetan @idiidk if at anytime the authcode changes again, please send a PR to https://github.com/simplyGits/magisterjs-authcode

**Pull request closed without merging**
